@php
    $channelNames = ['analytics' => 'Website analytics', 'seo' => 'SEO performance', 'social' => 'Social media', 'ads' => 'Advertising performance'];
    $campaigns = array_values(array_filter($adminData['campaigns'], fn($campaign) => match($active) { 'seo' => $campaign['platform'] === 'SEO', 'social' => $campaign['platform'] === 'Social Media', 'ads' => in_array($campaign['platform'], ['Google Ads', 'Meta Ads']), default => true }));
    $spend = array_sum(array_column($campaigns, 'spend'));
    $impressions = array_sum(array_column($campaigns, 'impressions'));
    $clicks = array_sum(array_column($campaigns, 'clicks'));
    $conversions = array_sum(array_column($campaigns, 'conversions'));
@endphp
<div class="workspace-heading"><div><h2>{{ $channelNames[$active] }}</h2><p>{{ $active === 'analytics' ? 'Audience and acquisition across your website.' : 'Performance from recorded campaigns in this channel.' }}</p></div><span class="badge">{{ $active === 'analytics' ? 'Sample data' : 'Manually recorded' }}</span></div>
@if($active === 'analytics')
    <p class="analytics-notice"><i data-lucide="info"></i>Sample website data. Connect a measurement provider before using these figures for business decisions.</p>
    <div class="kpi-grid">@foreach (['total_visitors' => 'Visitors', 'unique_visitors' => 'Unique visitors', 'bounce_rate' => 'Bounce rate', 'avg_session' => 'Average session'] as $key => $label)<article class="kpi"><div>{{ $label }}<i data-lucide="chart-no-axes-combined"></i></div><strong>{{ $analytics[$key] }}</strong><small>Sample data</small></article>@endforeach</div>
    <div class="dashboard-charts"><section class="chart-section"><div class="panel-title"><h2>Visitor trend</h2></div><div class="chart-wrap"><canvas data-chart="line" data-labels='["1", "2", "3", "4", "5", "6", "7"]' data-values='{{ json_encode($analytics["traffic_trend"]) }}' aria-label="Sample visitor trend" role="img"></canvas></div></section><section class="chart-section"><div class="panel-title"><h2>Devices</h2></div><div class="chart-wrap"><canvas data-chart="doughnut" data-labels='{{ json_encode(array_keys($analytics["devices"])) }}' data-values='{{ json_encode(array_values($analytics["devices"])) }}' aria-label="Sample device distribution" role="img"></canvas></div></section></div>
    <div class="admin-grid two-col"><section class="data-section"><h2>Traffic sources</h2><div class="responsive-table"><table><thead><tr><th>Source</th><th>Share</th></tr></thead><tbody>@foreach($analytics['sources'] as $source => $share)<tr><td>{{ $source }}</td><td>{{ $share }}%</td></tr>@endforeach</tbody></table></div></section><section class="data-section"><h2>Top pages</h2><div class="activity-list">@foreach($analytics['top_pages'] as $page)<div><span class="badge">{{ $loop->iteration }}</span><strong>{{ $page }}</strong></div>@endforeach</div></section></div>
@else
    @if(isset(\App\Http\Controllers\PlatformController::METRICS[$active]))
        @php
            $fields = \App\Http\Controllers\PlatformController::METRICS[$active];
            $snapshots = $adminData['marketing_metrics'][$active] ?? [];
            $latest = $snapshots ? end($snapshots) : [];
        @endphp
        <details class="record-editor" @if($errors->any()) open @endif><summary><i data-lucide="plus"></i>Record performance snapshot</summary><form class="form-grid" method="post" action="{{ route('admin.metrics.save', $active) }}">@csrf<label>Snapshot date<input type="date" name="date" required value="{{ old('date', now()->toDateString()) }}"></label>@foreach($fields as $key => $label)<label>{{ $label }}<input type="number" name="{{ $key }}" min="0" step="{{ in_array($key, ['domain_authority', 'search_visibility']) ? '0.01' : '1' }}" max="{{ in_array($key, ['domain_authority', 'search_visibility']) ? '100' : '999999999' }}" required value="{{ old($key, $latest[$key] ?? 0) }}"></label>@endforeach<button class="button button-primary" type="submit">Save snapshot</button></form></details>
        @if($latest)<div class="kpi-grid">@foreach($fields as $key => $label)<article class="kpi"><div>{{ $label }}</div><strong>{{ number_format($latest[$key], in_array($key, ['domain_authority', 'search_visibility']) ? 1 : 0) }}</strong><small>Recorded {{ $latest['date'] }}</small></article>@endforeach @if($active === 'social')<article class="kpi"><div>Engagement rate</div><strong>{{ $latest['reach'] ? round($latest['engagements'] / $latest['reach'] * 100, 2).'%' : '-' }}</strong><small>Engagements / reach</small></article>@endif</div><section class="chart-section"><div class="panel-title"><h2>{{ $active === 'seo' ? 'Organic traffic' : 'Followers' }} over time</h2></div><div class="chart-wrap"><canvas data-chart="line" data-labels='{{ json_encode(array_keys($snapshots)) }}' data-values='{{ json_encode(array_column($snapshots, $active === "seo" ? "organic_traffic" : "followers")) }}' aria-label="Recorded performance over time" role="img"></canvas></div></section>@endif
        <div class="panel-title"><h2>Campaign results</h2></div>
    @endif
    <div class="kpi-grid">@foreach (['Impressions' => number_format($impressions), 'Clicks' => number_format($clicks), 'Conversions' => number_format($conversions), 'Ad spend' => 'Rs '.number_format($spend), 'CTR' => $impressions ? round($clicks / $impressions * 100, 2).'%' : '-', 'CPC' => $clicks ? 'Rs '.number_format($spend / $clicks, 2) : '-', 'CPA' => $conversions ? 'Rs '.number_format($spend / $conversions, 2) : '-', 'ROAS' => $spend ? round(array_sum(array_column($campaigns, 'revenue')) / $spend, 2).'x' : '-'] as $label => $value)<article class="kpi"><div>{{ $label }}<i data-lucide="chart-no-axes-combined"></i></div><strong>{{ $value }}</strong><small>Recorded campaigns</small></article>@endforeach</div>
    @if(count($campaigns))<section class="chart-section"><div class="panel-title"><h2>Conversions by campaign</h2></div><div class="chart-wrap"><canvas data-chart="bar" data-labels='{{ json_encode(array_column($campaigns, "name")) }}' data-values='{{ json_encode(array_column($campaigns, "conversions")) }}' aria-label="Conversions by campaign" role="img"></canvas></div></section>@else<div class="empty-state"><i data-lucide="chart-no-axes-combined"></i><h3>No campaign data yet</h3><p>Add campaigns and record their performance to see this channel's results.</p>@if($canAccess('Campaigns'))<a class="button button-primary" href="{{ route('admin.platform.campaigns') }}">Create campaign <i data-lucide="plus"></i></a>@endif</div>@endif
    @if(in_array($active, ['seo', 'social']))<p class="analytics-notice"><i data-lucide="info"></i>Snapshots are manually recorded. Automatic updates require a connected provider.</p>@endif
@endif
