<div class="workspace-heading"><div><h2>Every lead is a new possibility</h2><p>Find the right conversation and keep it moving.</p></div>@if($canAccess('Lead Edit'))<a class="button button-primary" href="{{ route('admin.leads') }}"><i data-lucide="plus"></i>Add lead</a>@endif</div>
<div data-filter-table><div class="toolbar"><label>Search<input data-search type="search" placeholder="Name, email, or company"></label><label>Status<select data-filter="status"><option value="">All statuses</option>@foreach($adminData['lead_stages'] as $stage)<option>{{ $stage }}</option>@endforeach</select></label><label>Source<select data-filter="source"><option value="">All sources</option>@foreach(array_unique(array_column($adminData['leads'], 'source')) as $source)<option>{{ $source }}</option>@endforeach</select></label><label>Sort<select data-sort><option value="date">Newest first</option><option value="name">Name A-Z</option></select></label><label>From<input type="date" data-date-from></label><label>To<input type="date" data-date-to></label></div>
    @if($canAccess('Lead Edit'))<form id="bulk-leads" method="post" action="{{ route('admin.leads.bulk') }}" class="toolbar" data-confirm="Update the status of the selected leads?">@csrf<label>Selected leads<select name="stage">@foreach($adminData['lead_stages'] as $stage)<option>{{ $stage }}</option>@endforeach</select></label><button class="button button-ghost" type="submit">Update selected</button></form>@endif
    <div class="responsive-table"><table><thead><tr>@if($canAccess('Lead Edit'))<th><input type="checkbox" data-select-all aria-label="Select all visible leads"></th>@endif<th>Lead</th><th>Contact</th><th>Source / Service</th><th>Status</th><th>Score</th>@if($canAccess('Campaigns'))<th>Campaign</th>@endif<th>Assigned</th><th>Date</th><th>Details</th></tr></thead><tbody>
    @foreach($adminData['leads'] as $lead)<tr data-record data-name="{{ $lead['name'] }}" data-status="{{ $lead['stage'] }}" data-source="{{ $lead['source'] }}" data-date="{{ $lead['date'] }}">
        @if($canAccess('Lead Edit'))<td><input type="checkbox" name="ids[]" value="{{ $lead['id'] }}" form="bulk-leads" aria-label="Select {{ $lead['name'] }}"></td>@endif
        <td><strong>{{ $lead['name'] }}</strong><small>{{ $lead['business'] }}</small></td><td><a href="mailto:{{ $lead['email'] }}">{{ $lead['email'] }}</a><small>{{ $lead['phone'] }}</small></td><td>{{ $lead['source'] }}<small>{{ $lead['service'] }}</small></td><td>@if($canAccess('Lead Edit'))<form method="post" action="{{ route('admin.leads.stage', $lead['id']) }}">@csrf @method('patch')<select aria-label="Status for {{ $lead['name'] }}" name="stage" onchange="this.form.submit()">@foreach($adminData['lead_stages'] as $stage)<option @selected($lead['stage'] === $stage)>{{ $stage }}</option>@endforeach</select></form>@else<span class="badge">{{ $lead['stage'] }}</span>@endif</td><td>{{ $lead['score'] ?? '-' }}</td>@if($canAccess('Campaigns'))<td>{{ collect($adminData['campaigns'])->firstWhere('id', $lead['campaign_id'] ?? '')['name'] ?? 'Unassigned' }}</td>@endif<td>{{ $lead['assigned_to'] }}</td><td>{{ $lead['date'] }}</td><td><details class="row-details"><summary>View</summary><p><strong>Location:</strong> {{ $lead['location'] }}</p><p><strong>Package:</strong> {{ $lead['package'] }}</p><p><strong>Reminder:</strong> {{ $lead['reminder'] }}</p><p><strong>Notes:</strong> {{ $lead['notes'] }}</p><p><strong>Activity:</strong> {{ implode(', ', $lead['activity']) }}</p></details></td>
    </tr>@endforeach</tbody></table></div><p class="empty-state" data-empty @if(count($adminData['leads'])) hidden @endif>No matching leads. Adjust your filters or add a lead.</p>
</div>
