<div class="workspace-heading"><div><h2>Your business at a glance</h2><p>Every conversation. Every campaign. One clear view.</p></div><span class="date-label"><i data-lucide="calendar-days"></i>{{ now()->format('d M Y') }}</span></div>
<div class="kpi-grid">
    @if ($canAccess('Lead View'))<article class="kpi"><div><span>Total leads</span><i data-lucide="contact"></i></div><strong>{{ count($adminData['leads']) }}</strong><a href="{{ route('admin.leads.list') }}">View pipeline <i data-lucide="arrow-up-right"></i></a></article><article class="kpi"><div><span>Lead conversion</span><i data-lucide="target"></i></div><strong>{{ count($adminData['leads']) ? round(count(array_filter($adminData['leads'], fn($lead) => in_array($lead['stage'], ['Converted', 'Won'], true))) / count($adminData['leads']) * 100, 1) : 0 }}%</strong><small>Won leads / total leads</small></article>@endif
    @if ($canAccess('Invoices'))<article class="kpi"><div><span>Collected revenue</span><i data-lucide="indian-rupee"></i></div><strong>Rs {{ number_format($adminStats['revenue']) }}</strong><small>Recorded invoice payments</small></article>@endif
    @if ($canAccess('Campaigns'))<article class="kpi"><div><span>Active campaigns</span><i data-lucide="megaphone"></i></div><strong>{{ count(array_filter($adminData['campaigns'], fn($campaign) => $campaign['status'] === 'Active')) }}</strong><a href="{{ route('admin.platform.campaigns') }}">Manage campaigns <i data-lucide="arrow-up-right"></i></a></article>@endif
</div>
@if ($canAccess('Analytics'))
<div class="kpi-grid">
    <article class="kpi"><div><span>Website traffic</span><i data-lucide="globe"></i></div><strong>{{ number_format($analytics['total_visitors']) }}</strong><small>Sample website data</small></article>
    @if ($canAccess('Campaigns'))
        @php($recordedSpend = array_sum(array_column($adminData['campaigns'], 'spend')))
        <article class="kpi"><div><span>Ad spend</span><i data-lucide="wallet"></i></div><strong>Rs {{ number_format($recordedSpend) }}</strong><small>Recorded campaign totals</small></article>
        <article class="kpi"><div><span>ROAS</span><i data-lucide="trending-up"></i></div><strong>{{ $recordedSpend > 0 ? number_format(array_sum(array_column($adminData['campaigns'], 'revenue')) / $recordedSpend, 2).'x' : '-' }}</strong><small>Attributed revenue / spend</small></article>
    @endif
    @if ($canAccess('Clients'))<article class="kpi"><div><span>New clients</span><i data-lucide="building-2"></i></div><strong>{{ count(array_filter($adminData['clients'], fn($client) => str_starts_with($client['created_at'] ?? '', now()->format('Y-m')))) }}</strong><small>Added this month</small></article>@endif
</div>
<div class="analytics-notice"><i data-lucide="info"></i>Website analytics below are sample data from the existing workspace.</div>
<div class="dashboard-charts"><section class="chart-section"><div class="panel-title"><div><h2>Audience growth</h2><p>Visitor activity across seven sample periods</p></div><span class="badge">Sample data</span></div><div class="chart-wrap"><canvas data-chart="line" data-labels='["Period 1", "Period 2", "Period 3", "Period 4", "Period 5", "Period 6", "Period 7"]' data-values='{{ json_encode($analytics["traffic_trend"]) }}' aria-label="Sample website traffic" role="img"></canvas></div></section><section class="chart-section"><div class="panel-title"><h2>Traffic sources</h2><i data-lucide="chart-pie"></i></div><div class="chart-wrap compact"><canvas data-chart="doughnut" data-labels='{{ json_encode(array_keys($analytics["sources"])) }}' data-values='{{ json_encode(array_values($analytics["sources"])) }}' role="img" aria-label="Sample traffic source shares"></canvas></div></section></div>
@endif
<div class="dashboard-bottom">
    @if ($canAccess('Lead View'))<section class="data-section"><div class="panel-title"><h2>Recent leads</h2><a class="text-link" href="{{ route('admin.leads.list') }}">View all <i data-lucide="arrow-right"></i></a></div><div class="responsive-table"><table><thead><tr><th>Contact</th><th>Source</th><th>Status</th></tr></thead><tbody>@forelse (array_slice(array_reverse($adminData['leads']), 0, 5) as $lead)<tr><td><strong>{{ $lead['name'] }}</strong><small>{{ $lead['business'] }}</small></td><td>{{ $lead['source'] }}</td><td><span class="badge">{{ $lead['stage'] }}</span></td></tr>@empty<tr><td colspan="3">No leads yet.</td></tr>@endforelse</tbody></table></div></section>@endif
    @if ($canAccess('Audit Logs'))<section class="data-section"><div class="panel-title"><h2>Recent activity</h2><i data-lucide="history"></i></div><div class="activity-list">@foreach (array_slice(array_reverse($adminData['audit_logs']), 0, 5) as $log)<div><span class="activity-dot"></span><div><strong>{{ $log['action'] }}</strong><p>{{ $log['subject'] }}</p><small>{{ $log['date'] }}</small></div></div>@endforeach</div></section>@endif
</div>
