<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Adxon Performance Report</title><link rel="stylesheet" href="{{ asset('assets/platform.css') }}"><link rel="stylesheet" href="{{ asset('assets/workspace.css') }}"></head><body class="admin-body light-mode report-page"><div class="toolbar no-print"><a class="button secondary" href="{{ route('admin.reports') }}">Back to reports</a><button class="button primary" onclick="window.print()">Print / Save as PDF</button><a class="button secondary" href="{{ route('admin.reports.performance', array_merge(request()->only('from', 'to'), ['format' => 'csv'])) }}">Export CSV</a></div><img class="brand-logo" src="{{ asset('assets/brand/adxon-full-dark.png') }}" alt="Adxon"><h1>Marketing performance report</h1><p>{{ request('from') ?: 'All dates' }} to {{ request('to') ?: now()->toDateString() }} | Prepared {{ now()->format('d M Y') }}</p><p>{{ $settings['brand'] }} / {{ $settings['email'] }}</p><div class="kpi-grid">@foreach(['Campaigns' => count($data['campaigns']), 'Leads' => count($data['leads']), 'Ad spend' => 'Rs '.number_format(array_sum(array_column($data['campaigns'], 'spend'))), 'Invoice payments' => 'Rs '.number_format(array_sum(array_column($data['invoices'], 'paid')))] as $label => $value)<article class="kpi"><div>{{ $label }}</div><strong>{{ $value }}</strong></article>@endforeach</div><h2>Campaign performance</h2><div class="responsive-table"><table><thead><tr><th>Campaign</th><th>Channel</th><th>Status</th><th>Spend</th><th>Conversions</th><th>Revenue</th><th>ROAS</th></tr></thead><tbody>@forelse($data['campaigns'] as $campaign)<tr><td>{{ $campaign['name'] }}</td><td>{{ $campaign['platform'] }}</td><td>{{ $campaign['status'] }}</td><td>{{ number_format($campaign['spend'], 2) }}</td><td>{{ $campaign['conversions'] }}</td><td>{{ number_format($campaign['revenue'], 2) }}</td><td>{{ $campaign['spend'] ? round($campaign['revenue'] / $campaign['spend'], 2).'x' : '-' }}</td></tr>@empty<tr><td colspan="7">No recorded campaigns in this period.</td></tr>@endforelse</tbody></table></div><p>Campaign totals are manually recorded lifetime values for campaigns starting in the selected period. Lead and invoice totals use their creation dates. Currency: INR. Website sample analytics are excluded.</p>
@foreach ($data['marketing_metrics'] as $channel => $snapshots)
    @if ($snapshots)
        <section class="data-section">
            <h2>{{ ucfirst($channel) }} performance snapshots</h2>
            <div class="responsive-table"><table><thead><tr><th>Date</th>@foreach (\App\Http\Controllers\PlatformController::METRICS[$channel] ?? [] as $label)<th>{{ $label }}</th>@endforeach</tr></thead><tbody>
            @foreach ($snapshots as $snapshot)<tr><td>{{ $snapshot['date'] }}</td>@foreach (\App\Http\Controllers\PlatformController::METRICS[$channel] ?? [] as $key => $label)<td>{{ $snapshot[$key] }}</td>@endforeach</tr>@endforeach
            </tbody></table></div>
        </section>
    @endif
@endforeach
</body></html>
