@if ($active === 'campaigns')
    <div class="workspace-heading"><div><h2>Campaigns</h2><p>Plan, track, and refine your marketing investment.</p></div><span class="badge">{{ count($adminData['campaigns']) }} campaigns</span></div>
    @php($editing = collect($adminData['campaigns'])->firstWhere('id', request('edit')) ?? [])
    <details class="record-editor" @if($editing || $errors->any()) open @endif><summary><i data-lucide="plus"></i>{{ $editing ? 'Edit campaign' : 'Create campaign' }}</summary><form method="post" action="{{ route('admin.campaigns.save') }}" class="form-grid">@csrf
        <input type="hidden" name="id" value="{{ old('id', $editing['id'] ?? '') }}">
        <label>Campaign name<input name="name" required maxlength="160" value="{{ old('name', $editing['name'] ?? '') }}"></label>
        <label>Client<select name="client"><option value="">Unassigned</option>@foreach ($adminData['clients'] as $client)<option value="{{ $client['id'] }}" @selected(old('client', $editing['client'] ?? '') === $client['id'])>{{ $client['company'] }}</option>@endforeach</select></label>
        @foreach (['platform' => ['Google Ads', 'Meta Ads', 'SEO', 'Social Media', 'Email', 'Other'], 'type' => ['Awareness', 'Traffic', 'Lead Generation', 'Sales'], 'status' => ['Draft', 'Active', 'Paused', 'Completed']] as $field => $options)<label>{{ ucfirst($field) }}<select name="{{ $field }}">@foreach ($options as $option)<option @selected(old($field, $editing[$field] ?? '') === $option)>{{ $option }}</option>@endforeach</select></label>@endforeach
        <label>Start date<input type="date" name="start_date" required value="{{ old('start_date', $editing['start_date'] ?? now()->toDateString()) }}"></label>
        @foreach (['budget' => 'Budget (Rs)', 'spend' => 'Recorded spend (Rs)', 'impressions' => 'Impressions', 'clicks' => 'Clicks', 'conversions' => 'Conversions', 'revenue' => 'Attributed revenue (Rs)'] as $field => $label)<label>{{ $label }}<input type="number" name="{{ $field }}" min="0" max="999999999" step="{{ in_array($field, ['budget', 'spend', 'revenue']) ? '0.01' : '1' }}" required value="{{ old($field, $editing[$field] ?? 0) }}"></label>@endforeach
        <p class="wide analytics-notice">Campaign status and metrics are tracked in this workspace. Changes do not control external ad accounts.</p><button class="button button-primary" type="submit">Save campaign <i data-lucide="check"></i></button>
    </form></details>
    <div data-filter-table><div class="toolbar"><label>Search<input type="search" data-search placeholder="Campaign name"></label><label>Platform<select data-filter="platform"><option value="">All platforms</option>@foreach (['Google Ads', 'Meta Ads', 'SEO', 'Social Media', 'Email', 'Other'] as $platform)<option>{{ $platform }}</option>@endforeach</select></label><label>Status<select data-filter="status"><option value="">All statuses</option>@foreach (['Draft', 'Active', 'Paused', 'Completed'] as $status)<option>{{ $status }}</option>@endforeach</select></label><label>Type<select data-filter="type"><option value="">All types</option>@foreach (['Awareness', 'Traffic', 'Lead Generation', 'Sales'] as $type)<option>{{ $type }}</option>@endforeach</select></label><label>From<input type="date" data-date-from></label><label>To<input type="date" data-date-to></label></div>
    <div class="responsive-table"><table><thead><tr><th>Campaign</th><th>Platform</th><th>Budget / Spend</th><th>Impressions</th><th>Clicks</th><th>Conversions</th>@if($canAccess('Lead View'))<th>Leads</th>@endif<th>CTR</th><th>CPC</th><th>ROAS</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach ($adminData['campaigns'] as $campaign)<tr data-record data-platform="{{ $campaign['platform'] }}" data-status="{{ $campaign['status'] }}" data-type="{{ $campaign['type'] }}" data-date="{{ $campaign['start_date'] }}"><td><strong>{{ $campaign['name'] }}</strong><small>{{ $campaign['start_date'] }} / {{ $campaign['type'] }}</small></td><td>{{ $campaign['platform'] }}</td><td>Rs {{ number_format($campaign['budget']) }}<small>Rs {{ number_format($campaign['spend']) }} spent</small></td><td>{{ number_format($campaign['impressions']) }}</td><td>{{ number_format($campaign['clicks']) }}</td><td>{{ $campaign['conversions'] }}</td>@if($canAccess('Lead View'))<td>{{ count(array_filter($adminData['leads'], fn($lead) => ($lead['campaign_id'] ?? '') === $campaign['id'])) }}</td>@endif<td>{{ $campaign['impressions'] > 0 ? round($campaign['clicks'] / $campaign['impressions'] * 100, 2).'%' : '-' }}</td><td>{{ $campaign['clicks'] > 0 ? 'Rs '.number_format($campaign['spend'] / $campaign['clicks'], 2) : '-' }}</td><td>{{ $campaign['spend'] > 0 ? round($campaign['revenue'] / $campaign['spend'], 2).'x' : '-' }}</td><td><span class="badge">{{ $campaign['status'] }}</span></td><td><div class="table-actions"><a class="icon-button" title="Edit campaign" aria-label="Edit {{ $campaign['name'] }}" href="{{ route('admin.platform.campaigns', ['edit' => $campaign['id']]) }}"><i data-lucide="pencil"></i></a><form method="post" action="{{ route('admin.campaigns.status', $campaign['id']) }}">@csrf @method('patch')<input type="hidden" name="status" value="{{ $campaign['status'] === 'Active' ? 'Paused' : 'Active' }}"><button class="icon-button" title="{{ $campaign['status'] === 'Active' ? 'Pause' : 'Activate' }} campaign" aria-label="{{ $campaign['status'] === 'Active' ? 'Pause' : 'Activate' }} campaign"><i data-lucide="{{ $campaign['status'] === 'Active' ? 'pause' : 'play' }}"></i></button></form></div></td></tr>@endforeach</tbody></table></div><p class="empty-state" data-empty @if(count($adminData['campaigns'])) hidden @endif>No campaigns match. Create a campaign or adjust your filters.</p></div>
@elseif ($active === 'clients')
    <div class="workspace-heading"><div><h2>Client relationships</h2><p>The people and businesses behind the work.</p></div><span class="badge">{{ count($adminData['clients']) }} clients</span></div>
    @php($editing = collect($adminData['clients'])->firstWhere('id', request('edit')) ?? [])
    <details class="record-editor" @if($editing || $errors->any()) open @endif><summary><i data-lucide="plus"></i>{{ $editing ? 'Edit client' : 'Add client' }}</summary><form method="post" action="{{ route('admin.clients.save') }}" class="form-grid">@csrf<input type="hidden" name="id" value="{{ old('id', $editing['id'] ?? '') }}">@foreach (['name' => 'Contact name', 'company' => 'Company', 'email' => 'Email', 'phone' => 'Phone', 'industry' => 'Industry', 'team' => 'Assigned team'] as $field => $label)<label>{{ $label }}<input name="{{ $field }}" type="{{ $field === 'email' ? 'email' : 'text' }}" @required(in_array($field, ['name', 'company', 'email'])) value="{{ old($field, $editing[$field] ?? '') }}"></label>@endforeach<label>Status<select name="status">@foreach (['Onboarding', 'Active', 'Inactive'] as $status)<option @selected(old('status', $editing['status'] ?? '') === $status)>{{ $status }}</option>@endforeach</select></label><label class="wide">Communication notes<textarea name="notes" rows="4" maxlength="5000">{{ old('notes', $editing['notes'] ?? '') }}</textarea></label><button class="button button-primary" type="submit">Save client <i data-lucide="check"></i></button></form></details>
    <div data-filter-table><div class="toolbar"><label>Search clients<input type="search" data-search placeholder="Name, company, or email"></label><label>Status<select data-filter="status"><option value="">All statuses</option><option>Active</option><option>Onboarding</option><option>Inactive</option></select></label></div><div class="client-grid">@foreach ($adminData['clients'] as $client)<article class="client-card" data-record data-status="{{ $client['status'] }}"><span class="avatar">{{ substr($client['company'], 0, 1) }}</span><h3>{{ $client['company'] }}</h3><p>{{ $client['name'] }} / {{ $client['industry'] }}</p><p><a href="mailto:{{ $client['email'] }}">{{ $client['email'] }}</a></p><span class="badge">{{ $client['status'] }}</span><details><summary>Client details</summary><p>Phone: {{ $client['phone'] ?: '-' }}<br>Team: {{ $client['team'] ?: 'Unassigned' }}<br>Client since: {{ $client['created_at'] }}</p><p>{{ $client['notes'] }}</p>
        @if($canAccess('Campaigns'))<strong>Campaigns</strong>@forelse(array_filter($adminData['campaigns'], fn($campaign) => $campaign['client'] === $client['id']) as $campaign)<p>{{ $campaign['name'] }} / {{ $campaign['status'] }}<br>{{ $campaign['conversions'] }} conversions</p>@empty<p>No linked campaigns.</p>@endforelse @endif
        @if($canAccess('Invoices'))<strong>Billing</strong>@forelse(array_filter($adminData['invoices'], fn($invoice) => ($invoice['business'] ?? '') === $client['company'] || ($invoice['customer'] ?? '') === $client['company']) as $invoice)<p>{{ $invoice['invoice_no'] }} / Rs {{ number_format($invoice['balance']) }} outstanding</p>@empty<p>No matching invoices.</p>@endforelse @endif
    </details><a class="text-link" href="{{ route('admin.platform.clients', ['edit' => $client['id']]) }}">Edit client <i data-lucide="pencil"></i></a></article>@endforeach</div><p class="empty-state" data-empty @if(count($adminData['clients'])) hidden @endif>No clients match. Add a client or adjust your filters.</p></div>
@elseif (in_array($active, ['analytics', 'seo', 'social', 'ads']))
    @include('admin.analytics')
@elseif ($active === 'messages')
    <div class="workspace-heading"><div><h2>Messages & notifications</h2><p>Website enquiries and recent workspace updates.</p></div><a class="button button-ghost" href="{{ route('admin.enquiries') }}">Manage enquiries <i data-lucide="arrow-right"></i></a></div><div class="admin-grid two-col"><section class="data-section"><h2>Inbox</h2><div class="activity-list">@forelse(array_reverse($content['enquiries']) as $enquiry)<div><span class="avatar">{{ substr($enquiry['name'], 0, 1) }}</span><div><strong>{{ $enquiry['name'] }}</strong><p>{{ $enquiry['message'] }}</p><small>{{ $enquiry['created_at'] }}</small><p><a href="mailto:{{ $enquiry['email'] }}">Reply to {{ $enquiry['email'] }}</a></p></div></div>@empty<p class="empty-state">No enquiries yet.</p>@endforelse</div></section><section class="data-section"><h2>Notifications</h2><div class="activity-list">@forelse(($preferences['notifications'] ? array_slice(array_reverse($adminData['notifications']), 0, 20) : []) as $notification)<div><span class="activity-dot"></span><div><strong>{{ $notification['message'] }}</strong><p>{{ $notification['date'] }}</p></div></div>@empty<p>{{ $preferences['notifications'] ? 'No notifications.' : 'Notifications are muted for this account.' }}</p>@endforelse</div></section></div>
@elseif ($active === 'preferences')
    <div class="workspace-heading"><div><h2>Account & settings</h2><p>Your profile, workspace, and connected services.</p></div></div>
    <form class="form-grid admin-panel" method="post" action="{{ route('admin.preferences.save') }}">@csrf
        <h2>Profile & notifications</h2>
        <label>Display name<input name="display_name" required maxlength="120" value="{{ old('display_name', $preferences['display_name'] ?: session('adxon_user.name')) }}"></label>
        <input type="hidden" name="notifications" value="0">
        <label class="checkbox-label"><input type="checkbox" name="notifications" value="1" @checked(old('notifications', $preferences['notifications']))>Show workspace notifications</label>
        <button class="button button-primary" type="submit">Save preferences</button>
    </form>
    <div class="settings-links"><div><h3><i data-lucide="user-round"></i>Account</h3><p>{{ session('adxon_user.email') }}<br>{{ session('adxon_user.role') }}</p></div>
        @if($canAccess('CMS'))<a href="{{ route('admin.settings') }}"><h3><i data-lucide="building-2"></i>Company & website</h3><p>Business details, typography, hero content, and search metadata.</p></a>@endif
        @if($canAccess('User Management'))<a href="{{ route('admin.users') }}"><h3><i data-lucide="users"></i>Team & permissions</h3><p>Team members, roles, and access to workspace modules.</p></a>@endif
        @if($canAccess('Invoices'))<a href="{{ route('admin.invoices.list') }}"><h3><i data-lucide="receipt"></i>Billing</h3><p>Invoices, recorded payments, and outstanding balances.</p></a>@endif
        <div><h3><i data-lucide="plug"></i>Integrations & API</h3><p>No marketing provider is connected. Campaign metrics are recorded manually; website analytics are sample data.</p></div><div><h3><i data-lucide="shield-check"></i>Security</h3><p>This session uses your assigned role permissions.</p><form method="post" action="{{ route('admin.logout') }}">@csrf<button class="button button-ghost" type="submit">Sign out of this session</button></form></div></div>
@endif
